# Generated by Django 5.0 on 2023-12-06 17:16

from os import getenv
from typing import TYPE_CHECKING, cast
from django.db import migrations


def create_superuser(apps, schema_editor):
    User = cast("UserModel", apps.get_model("user", "User"))
    user = User.objects.create_superuser(
        username=getenv("DJANGO_ADMIN_USERNAME", "admin"),
        password=getenv("DJANGO_ADMIN_PASSWORD", "admin"),
        email=getenv("DJANGO_ADMIN_EMAIL", "admin@admin.com"),
    )
    Group = apps.get_model("auth", "Group")
    admin_group, _ = Group.objects.get_or_create(name="Admin")
    user.groups.add(admin_group)


def delete_superuser(apps, schema_editor):
    User = cast("UserModel", apps.get_model("user", "User"))
    username = getenv("DJANGO_ADMIN_USERNAME", "admin")

    try:
        user = User.objects.get(username=username)
        user.delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_create_default_groups"),
    ]

    operations = [
        migrations.RunPython(create_superuser, delete_superuser),
    ]
